#name: dev pull request
#
#on:
#  pull_request:
#    types: [opened, edited, synchronize]
#    branches:
#      - dev
#
#jobs:
#  dev-test:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Github Repository 파일 불러오기
#        uses: actions/checkout@v4
#
#      - name: JDK v17 설치
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#          cache: gradle
#
#      - name: application.yml 파일 만들기
#        run: echo '${{ secrets.APPLICATION_PROPERTIES }}' > ./src/main/resources/application.yml
#
#      - name: 빌드하기 및 테스트 하기
#        run: ./gradlew clean build
#
#      - name: Upload Test Report
#        if: always()
#        uses: actions/upload-artifact@v3
#        with:
#          name: test-report
#          path: build/reports/tests/test
